language: groovy
jdk:
  - openjdk8
sudo: required

services:
  - docker

addons:
  node_js: "9"

script:
  - gradle build && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && gradle deploy