name: Build on Push and PR
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build OCD3
      run: ./gradlew build
    - name: Deploy OCD3
      if: github.event_name != 'pull_request'
      run: ./gradlew deploy
      env:
        mksRepoUrl: 'https://nexus.mekomsolutions.net/repository/maven-snapshots'
        mksRepoUsername: "${{ secrets.NEXUS_USERNAME }}"
        mksRepoPassword: "${{ secrets.NEXUS_PASSWORD }}"