name: Build on Push and PR
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    - name: Build OCD3
      run: ./gradlew build
    - name: Deploy OCD3
      run: ./gradlew deploy